version: "3"
services:
  web:
    image: pykafka/base:latest
    container_name: webapp
    env_file:
      - docker-env
    command: python /opt/eda-demo/app.py
    volumes:
      - .:/opt/eda-demo/
    ports:
      - '5000:5000'

  p0:
    image: pykafka/base:latest
    container_name: producer_0
    env_file:
      - docker-env
    command: python /opt/eda-demo/producers/parse_website_changes.py
    volumes:
      - .:/opt/eda-demo/
    expose:
      - 8001  # TODO kafka ports

  p1:
    image: pykafka/base:latest
    container_name: producer_1
    env_file:
      - docker-env
    command: python /opt/eda-demo/producers/calculate_pagerank.py
    volumes:
      - .:/opt/eda-demo/
    expose:
      - 8001  # TODO kafka ports
    depends_on:
      - p0

  p2:
    image: pykafka/base:latest
    container_name: producer_2
    env_file:
      - docker-env
    command: python /opt/eda-demo/producers/website_ner.py
    volumes:
      - .:/opt/eda-demo/
    expose:
      - 8001  # TODO kafka ports
    depends_on:
      - p0

  p3:
    image: pykafka/base:latest
    container_name: producer_3
    env_file:
      - docker-env
    command: python /opt/eda-demo/producers/website_relevancy.py
    volumes:
      - .:/opt/eda-demo/
    expose:
      - 8001  # TODO kafka ports
    depends_on:
      - p1
      - p2

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
